import { select } from "@storybook/addon-knobs";
import { html, TemplateResult } from "lit-html";

export default {
  component: "core-icon",
  title: "Misc Components/Icon",
};

const colors = {
  "--": "--",
  blue: "blue",
  green: "green",
  yellow: "yellow",
  red: "red",
  white: "white",
  black: "black",
  "blue-light-4": "blue-light-4",
  "blue-light-3": "blue-light-3",
  "blue-light-2": "blue-light-2",
  "blue-light-1": "blue-light-1",
  "blue-dark-1": "blue-dark-1",
  "blue-dark-2": "blue-dark-2",
  "blue-dark-3": "blue-dark-3",
  "blue-dark-4": "blue-dark-4",
  "green-light-4": "green-light-4",
  "green-light-3": "green-light-3",
  "green-light-2": "green-light-2",
  "green-light-1": "green-light-1",
  "green-dark-1": "green-dark-1",
  "green-dark-2": "green-dark-2",
  "green-dark-3": "green-dark-3",
  "green-dark-4": "green-dark-4",
  "yellow-light-4": "yellow-light-4",
  "yellow-light-3": "yellow-light-3",
  "yellow-light-2": "yellow-light-2",
  "yellow-light-1": "yellow-light-1",
  "yellow-dark-1": "yellow-dark-1",
  "yellow-dark-2": "yellow-dark-2",
  "yellow-dark-3": "yellow-dark-3",
  "yellow-dark-4": "yellow-dark-4",
  "red-light-4": "red-light-4",
  "red-light-3": "red-light-3",
  "red-light-2": "red-light-2",
  "red-light-1": "red-light-1",
  "red-dark-1": "red-dark-1",
  "red-dark-2": "red-dark-2",
  "red-dark-3": "red-dark-3",
  "red-dark-4": "red-dark-4",
  "gray-1": "gray-1",
  "gray-2": "gray-2",
  "gray-3": "gray-3",
  "gray-4": "gray-4",
  "gray-5": "gray-5",
  "gray-6": "gray-6",
  "gray-7": "gray-7",
  "gray-8": "gray-8",
};

const icons = {
  "alert-circle": "alert-circle",
  "alert-triangle": "alert-triangle",
  "alert-triangle-solid": "alert-triangle-solid",
  anchor: "anchor",
  archive: "archive",
  "arrow-down": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-up": "arrow-up",
  bar: "bar",
  bell: "bell",
  "bell-mute": "bell-mute",
  "bell-solid": "bell-solid",
  bold: "bold",
  bullet: "bullet",
  calendar: "calendar",
  camera: "camera",
  "caret-down": "caret-down",
  "caret-left": "caret-left",
  "caret-right": "caret-right",
  "caret-up": "caret-up",
  cart: "cart",
  "cart-solid": "cart-solid",
  category: "category",
  check: "check",
  "check-sm": "check-sm",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "chevron-up": "chevron-up",
  circle: "circle",
  clipboard: "clipboard",
  clock: "clock",
  columns: "columns",
  cross: "cross",
  "cross-sm": "cross-sm",
  disable: "disable",
  dot: "dot",
  download: "download",
  drag: "drag",
  "fast-forward": "fast-forward",
  "film-camera": "film-camera",
  gear: "gear",
  globe: "globe",
  grad: "grad",
  grid: "grid",
  heading: "heading",
  heart: "heart",
  help: "help",
  "help-solid": "help-solid",
  history: "history",
  hourglass: "hourglass",
  image: "image",
  info: "info",
  italic: "italic",
  layers: "layers",
  link: "link",
  "link-out": "link-out",
  "list-bullet": "list-bullet",
  "list-num": "list-num",
  logout: "logout",
  mail: "mail",
  "mail-solid": "mail-solid",
  menu: "menu",
  meter: "meter",
  minus: "minus",
  "minus-box": "minus-box",
  more: "more",
  paragraph: "paragraph",
  pen: "pen",
  pencil: "pencil",
  play: "play",
  plus: "plus",
  "plus-box": "plus-box",
  quote: "quote",
  redo: "redo",
  refresh: "refresh",
  rewind: "rewind",
  rows: "rows",
  search: "search",
  settings: "settings",
  speech: "speech",
  spinner: "spinner",
  star: "star",
  "star-half": "star-half",
  "star-solid": "star-solid",
  strike: "strike",
  toolbox: "toolbox",
  trash: "trash",
  underline: "underline",
  undo: "undo",
  user: "user",
  users: "users",
  video: "video",
};

export const PropStates = (): TemplateResult => {
  return html`
    <core-icon
      color="${select("Color", colors, "gray-5")}"
      icon="${select("Icon", icons, "alert-circle")}"
    ></core-icon>
  `;
};

export const Default = (): TemplateResult => {
  return html`
    <core-icon icon="alert-circle"></core-icon>
  `;
};
