/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { colorsAll, colorsPrimary, iconsAll, labelPosition } from "./global/script/global";
export namespace Components {
    interface CoreAlert {
        /**
          * Optional color of the element.
         */
        "color"?: "gray" | "green" | "yellow" | "red";
    }
    interface CoreBadge {
        /**
          * Color of the element.
         */
        "color"?: "black" | "red";
        /**
          * The pre-defined element size.
         */
        "size"?: "small" | "large";
        /**
          * The element variation.
         */
        "variation"?: "border" | "dot" | "fill";
    }
    interface CoreButton {
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled": boolean;
        /**
          * Specifies [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display) of the custom element.
         */
        "display"?: "block" | "flex" | "inline" | "inlineFlex" | "none";
        /**
          * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
         */
        "download": string | undefined;
        /**
          * The type of element.
         */
        "elementType": string;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered instead of a button.
         */
        "href": string | undefined;
        /**
          * Specifies the loading animation location if applied.
         */
        "loading"?: "left" | "right" | "only";
        /**
          * Set to the value of border-radius applied. Default is 4(px).
         */
        "radius"?: "0" | "4" | "circle";
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
         */
        "rel": string | undefined;
        /**
          * The pre-defined button size.
         */
        "size"?: "small" | "default" | "large";
        /**
          * The status classing of the button.
         */
        "status": "success" | "danger" | "warning";
        /**
          * Specifies where to display the linked URL. Only applies when an `href` is provided.
         */
        "target": string | undefined;
        /**
          * The type of the button.
         */
        "type": "submit" | "reset" | "button";
        /**
          * The button variation.
         */
        "variation"?: | "basic"
    | "primary"
    | "secondary"
    | "dark"
    | "light"
    | "borderless";
        /**
          * Set to "full" for a 100% full-width button without border-radius/borders or to "block"`.
         */
        "width"?: "full" | "block" | undefined;
    }
    interface CoreCheckbox {
        /**
          * If applied, the element is checked.
         */
        "checked": boolean;
        /**
          * Optional color of the label (inherited). Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll;
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled": boolean;
        /**
          * The label element associated with the element.
         */
        "label": string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required": boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreDropdown {
        /**
          * The dropdown visibility
         */
        "active": boolean;
        /**
          * The element alignment
         */
        "alignment"?: "left" | "center" | "right";
        /**
          * The dropdown will show up when hovering the dropdown-trigger
         */
        "hoverable": boolean;
        /**
          * The dropdown will wrap if applied.
         */
        "wrap": boolean;
    }
    interface CoreDropdownItem {
        /**
          * The type of element.
         */
        "elementType": string;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered instead of a div.
         */
        "href": string | undefined;
        /**
          * Specifies where to display the linked URL. Only applies when an `href` is provided.
         */
        "target": string | undefined;
    }
    interface CoreIcon {
        /**
          * Specifies the label to use for accessibility. Defaults to the icon name.
         */
        "ariaLabel"?: string;
        /**
          * Optional color of the icon. Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll | string;
        /**
          * A combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
         */
        "icon"?: iconsAll | string;
        /**
          * If enabled, core-icon will be loaded lazily when it's visible in the viewport.
         */
        "lazy": boolean;
        /**
          * Specifies which icon to use from `src/core-icons`.
         */
        "name"?: string;
        /**
          * The size of the icon. Available options are: `"16"` and `"24"`.
         */
        "size"?: "16" | "24";
        /**
          * Specifies the exact `src` of an SVG file to use.
         */
        "src"?: string;
    }
    interface CoreInput {
        /**
          * Boolean attribute lets you specify that a form control should have input focus when the page loads.
         */
        "autofocus": boolean;
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearInput": boolean;
        /**
          * Optional color of the label (inherited). Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll;
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled": boolean;
        /**
          * If `true`, the pre-defined error state is applied.
         */
        "error": boolean;
        /**
          * The core-icon to render inside the text input.
         */
        "icon"?: string;
        /**
          * A hint to the browser for which keyboard to display.
         */
        "inputkeyboard"?: | "none"
    | "text"
    | "tel"
    | "url"
    | "email"
    | "numeric"
    | "decimal"
    | "search";
        /**
          * The label element associated with the element.
         */
        "label": string | undefined;
        /**
          * Sets the optional label to `inline` or `block` style [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display).
         */
        "labelDisplay"?: "block" | "inline";
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * Instructional placeholder text that shows before the element has a value.
         */
        "placeholder"?: string | undefined;
        /**
          * If `true`, the user must fill in a value before submitting a form.
         */
        "required": boolean;
        /**
          * Apply the large pre-defined element size and styling.
         */
        "size"?: "large";
        /**
          * If `true`, the pre-defined success state is applied.
         */
        "success": boolean;
        /**
          * How an <input> works varies considerably depending on the value of its type attribute, hence the different types are covered in their own separate reference pages. If this attribute is not specified, the default type adopted is `text`. [<input> types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
         */
        "type"?: string;
    }
    interface CoreLabel {
        /**
          * Optional color of the label. Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: | "blue"
    | "green"
    | "yellow"
    | "red"
    | "white"
    | "black"
    | "blue-light-4"
    | "blue-light-3"
    | "blue-light-2"
    | "blue-light-1"
    | "blue-dark-1"
    | "blue-dark-2"
    | "blue-dark-3"
    | "blue-dark-4"
    | "green-light-4"
    | "green-light-3"
    | "green-light-2"
    | "green-light-1"
    | "green-dark-1"
    | "green-dark-2"
    | "green-dark-3"
    | "green-dark-4"
    | "yellow-light-4"
    | "yellow-light-3"
    | "yellow-light-2"
    | "yellow-light-1"
    | "yellow-dark-1"
    | "yellow-dark-2"
    | "yellow-dark-3"
    | "yellow-dark-4"
    | "red-light-4"
    | "red-light-3"
    | "red-light-2"
    | "red-light-1"
    | "red-dark-1"
    | "red-dark-2"
    | "red-dark-3"
    | "red-dark-4"
    | "gray-1"
    | "gray-2"
    | "gray-3"
    | "gray-4"
    | "gray-5"
    | "gray-6"
    | "gray-7"
    | "gray-8"
    | string;
        /**
          * If `true`, the user cannot interact with the nested element (typically core-input).
         */
        "disabled": boolean;
        /**
          * The display determines where and how the label behaves inside an item.
         */
        "display"?: "inline" | "block";
        /**
          * Applies the provided URL to the helpIcon href.
         */
        "helpurl"?: string | undefined;
    }
    interface CorePopover {
        /**
          * The popover visibility
         */
        "active": boolean;
        /**
          * The popover will show up when hovering the popover-trigger
         */
        "hoverable": boolean;
        /**
          * The popover variation.
         */
        "variation"?: "top" | "bottom";
    }
    interface CoreProgress {
        /**
          * Color of the progress bar.
         */
        "color"?: colorsPrimary;
        /**
          * The progress bar maximum value.
         */
        "max": number;
        /**
          * The pre-defined progress bar size.
         */
        "size"?: "small" | "large";
        /**
          * The progress bar value.
         */
        "value": number | undefined;
    }
    interface CoreRadio {
        /**
          * If applied, the element is checked.
         */
        "checked": boolean;
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled": boolean;
        /**
          * The label element associated with the element.
         */
        "label": string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required": boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreSpinner {
        /**
          * Color of the spinner.
         */
        "color"?: colorsPrimary;
        /**
          * The pre-defined spinner size.
         */
        "size"?: "small" | "medium" | "large";
    }
    interface CoreTab {
        /**
          * If `true`, the tab element is set to active.
         */
        "active": boolean;
        /**
          * If `true`, the user cannot interact with the tab.
         */
        "disabled": boolean;
    }
    interface CoreTabGroup {
        /**
          * The pre-defined tab size.
         */
        "size": "small" | "large";
    }
    interface CoreTag {
        /**
          * Allows the tag to be closable and removed from the view.
         */
        "closable": boolean;
        /**
          * Optional color of the tag. Defaults to `black`. Use the following `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsPrimary;
        /**
          * The pre-defined tag size.
         */
        "size"?: "small" | "large";
        /**
          * The tag variation.
         */
        "variation"?: "default" | "light";
    }
    interface CoreTextarea {
        /**
          * The visible width of the text control, in average character widths. If it is specified, it must be a positive integer.
         */
        "cols"?: number;
        /**
          * If `true`, the user cannot interact with the textarea.
         */
        "disabled": boolean;
        /**
          * Returns the native `<textarea>` element used under the hood.
         */
        "getInputElement": () => Promise<HTMLTextAreaElement>;
        /**
          * The label element associated with the element.
         */
        "label": string | undefined;
        /**
          * Sets the optional label to `inline` or `block` style [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display).
         */
        "labelDisplay"?: "block" | "inline";
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * Instructional text that shows before the input has a value.
         */
        "placeholder"?: string | undefined;
        /**
          * If `true`, the user must fill in a value before submitting a form.
         */
        "required": boolean;
        /**
          * The number of visible text lines for the control.
         */
        "rows"?: number;
        /**
          * The value of the textarea.
         */
        "value"?: string | null;
    }
    interface CoreToast {
        /**
          * Optional color of the toast. Defaults to `black`.
         */
        "color"?: "white" | "green" | "yellow" | "red";
    }
    interface CoreToggle {
        /**
          * If applied, the element is rendered with the alternate styling.
         */
        "alt": boolean;
        /**
          * If applied, the element is checked.
         */
        "checked": boolean;
        /**
          * Optional color of the icon. Defaults to `blue`. Use the following `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: "green" | "yellow" | "red" | "black" | "blue";
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled": boolean;
        /**
          * The label element associated with the element.
         */
        "label": string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required": boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreTooltip {
        /**
          * The tooltip visibility
         */
        "active": boolean;
        /**
          * The tooltip color
         */
        "color"?: "dark" | "light";
        /**
          * The tooltip will show up when hovering the tooltip-trigger
         */
        "hoverable": boolean;
        /**
          * The tooltip variation.
         */
        "variation"?: "top" | "bottom";
    }
}
declare global {
    interface HTMLCoreAlertElement extends Components.CoreAlert, HTMLStencilElement {
    }
    var HTMLCoreAlertElement: {
        prototype: HTMLCoreAlertElement;
        new (): HTMLCoreAlertElement;
    };
    interface HTMLCoreBadgeElement extends Components.CoreBadge, HTMLStencilElement {
    }
    var HTMLCoreBadgeElement: {
        prototype: HTMLCoreBadgeElement;
        new (): HTMLCoreBadgeElement;
    };
    interface HTMLCoreButtonElement extends Components.CoreButton, HTMLStencilElement {
    }
    var HTMLCoreButtonElement: {
        prototype: HTMLCoreButtonElement;
        new (): HTMLCoreButtonElement;
    };
    interface HTMLCoreCheckboxElement extends Components.CoreCheckbox, HTMLStencilElement {
    }
    var HTMLCoreCheckboxElement: {
        prototype: HTMLCoreCheckboxElement;
        new (): HTMLCoreCheckboxElement;
    };
    interface HTMLCoreDropdownElement extends Components.CoreDropdown, HTMLStencilElement {
    }
    var HTMLCoreDropdownElement: {
        prototype: HTMLCoreDropdownElement;
        new (): HTMLCoreDropdownElement;
    };
    interface HTMLCoreDropdownItemElement extends Components.CoreDropdownItem, HTMLStencilElement {
    }
    var HTMLCoreDropdownItemElement: {
        prototype: HTMLCoreDropdownItemElement;
        new (): HTMLCoreDropdownItemElement;
    };
    interface HTMLCoreIconElement extends Components.CoreIcon, HTMLStencilElement {
    }
    var HTMLCoreIconElement: {
        prototype: HTMLCoreIconElement;
        new (): HTMLCoreIconElement;
    };
    interface HTMLCoreInputElement extends Components.CoreInput, HTMLStencilElement {
    }
    var HTMLCoreInputElement: {
        prototype: HTMLCoreInputElement;
        new (): HTMLCoreInputElement;
    };
    interface HTMLCoreLabelElement extends Components.CoreLabel, HTMLStencilElement {
    }
    var HTMLCoreLabelElement: {
        prototype: HTMLCoreLabelElement;
        new (): HTMLCoreLabelElement;
    };
    interface HTMLCorePopoverElement extends Components.CorePopover, HTMLStencilElement {
    }
    var HTMLCorePopoverElement: {
        prototype: HTMLCorePopoverElement;
        new (): HTMLCorePopoverElement;
    };
    interface HTMLCoreProgressElement extends Components.CoreProgress, HTMLStencilElement {
    }
    var HTMLCoreProgressElement: {
        prototype: HTMLCoreProgressElement;
        new (): HTMLCoreProgressElement;
    };
    interface HTMLCoreRadioElement extends Components.CoreRadio, HTMLStencilElement {
    }
    var HTMLCoreRadioElement: {
        prototype: HTMLCoreRadioElement;
        new (): HTMLCoreRadioElement;
    };
    interface HTMLCoreSpinnerElement extends Components.CoreSpinner, HTMLStencilElement {
    }
    var HTMLCoreSpinnerElement: {
        prototype: HTMLCoreSpinnerElement;
        new (): HTMLCoreSpinnerElement;
    };
    interface HTMLCoreTabElement extends Components.CoreTab, HTMLStencilElement {
    }
    var HTMLCoreTabElement: {
        prototype: HTMLCoreTabElement;
        new (): HTMLCoreTabElement;
    };
    interface HTMLCoreTabGroupElement extends Components.CoreTabGroup, HTMLStencilElement {
    }
    var HTMLCoreTabGroupElement: {
        prototype: HTMLCoreTabGroupElement;
        new (): HTMLCoreTabGroupElement;
    };
    interface HTMLCoreTagElement extends Components.CoreTag, HTMLStencilElement {
    }
    var HTMLCoreTagElement: {
        prototype: HTMLCoreTagElement;
        new (): HTMLCoreTagElement;
    };
    interface HTMLCoreTextareaElement extends Components.CoreTextarea, HTMLStencilElement {
    }
    var HTMLCoreTextareaElement: {
        prototype: HTMLCoreTextareaElement;
        new (): HTMLCoreTextareaElement;
    };
    interface HTMLCoreToastElement extends Components.CoreToast, HTMLStencilElement {
    }
    var HTMLCoreToastElement: {
        prototype: HTMLCoreToastElement;
        new (): HTMLCoreToastElement;
    };
    interface HTMLCoreToggleElement extends Components.CoreToggle, HTMLStencilElement {
    }
    var HTMLCoreToggleElement: {
        prototype: HTMLCoreToggleElement;
        new (): HTMLCoreToggleElement;
    };
    interface HTMLCoreTooltipElement extends Components.CoreTooltip, HTMLStencilElement {
    }
    var HTMLCoreTooltipElement: {
        prototype: HTMLCoreTooltipElement;
        new (): HTMLCoreTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "core-alert": HTMLCoreAlertElement;
        "core-badge": HTMLCoreBadgeElement;
        "core-button": HTMLCoreButtonElement;
        "core-checkbox": HTMLCoreCheckboxElement;
        "core-dropdown": HTMLCoreDropdownElement;
        "core-dropdown-item": HTMLCoreDropdownItemElement;
        "core-icon": HTMLCoreIconElement;
        "core-input": HTMLCoreInputElement;
        "core-label": HTMLCoreLabelElement;
        "core-popover": HTMLCorePopoverElement;
        "core-progress": HTMLCoreProgressElement;
        "core-radio": HTMLCoreRadioElement;
        "core-spinner": HTMLCoreSpinnerElement;
        "core-tab": HTMLCoreTabElement;
        "core-tab-group": HTMLCoreTabGroupElement;
        "core-tag": HTMLCoreTagElement;
        "core-textarea": HTMLCoreTextareaElement;
        "core-toast": HTMLCoreToastElement;
        "core-toggle": HTMLCoreToggleElement;
        "core-tooltip": HTMLCoreTooltipElement;
    }
}
declare namespace LocalJSX {
    interface CoreAlert {
        /**
          * Optional color of the element.
         */
        "color"?: "gray" | "green" | "yellow" | "red";
    }
    interface CoreBadge {
        /**
          * Color of the element.
         */
        "color"?: "black" | "red";
        /**
          * The pre-defined element size.
         */
        "size"?: "small" | "large";
        /**
          * The element variation.
         */
        "variation"?: "border" | "dot" | "fill";
    }
    interface CoreButton {
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled"?: boolean;
        /**
          * Specifies [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display) of the custom element.
         */
        "display"?: "block" | "flex" | "inline" | "inlineFlex" | "none";
        /**
          * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
         */
        "download"?: string | undefined;
        /**
          * The type of element.
         */
        "elementType"?: string;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered instead of a button.
         */
        "href"?: string | undefined;
        /**
          * Specifies the loading animation location if applied.
         */
        "loading"?: "left" | "right" | "only";
        /**
          * Set to the value of border-radius applied. Default is 4(px).
         */
        "radius"?: "0" | "4" | "circle";
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
         */
        "rel"?: string | undefined;
        /**
          * The pre-defined button size.
         */
        "size"?: "small" | "default" | "large";
        /**
          * The status classing of the button.
         */
        "status"?: "success" | "danger" | "warning";
        /**
          * Specifies where to display the linked URL. Only applies when an `href` is provided.
         */
        "target"?: string | undefined;
        /**
          * The type of the button.
         */
        "type"?: "submit" | "reset" | "button";
        /**
          * The button variation.
         */
        "variation"?: | "basic"
    | "primary"
    | "secondary"
    | "dark"
    | "light"
    | "borderless";
        /**
          * Set to "full" for a 100% full-width button without border-radius/borders or to "block"`.
         */
        "width"?: "full" | "block" | undefined;
    }
    interface CoreCheckbox {
        /**
          * If applied, the element is checked.
         */
        "checked"?: boolean;
        /**
          * Optional color of the label (inherited). Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll;
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The label element associated with the element.
         */
        "label"?: string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required"?: boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreDropdown {
        /**
          * The dropdown visibility
         */
        "active"?: boolean;
        /**
          * The element alignment
         */
        "alignment"?: "left" | "center" | "right";
        /**
          * The dropdown will show up when hovering the dropdown-trigger
         */
        "hoverable"?: boolean;
        /**
          * The dropdown will wrap if applied.
         */
        "wrap"?: boolean;
    }
    interface CoreDropdownItem {
        /**
          * The type of element.
         */
        "elementType"?: string;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered instead of a div.
         */
        "href"?: string | undefined;
        /**
          * Specifies where to display the linked URL. Only applies when an `href` is provided.
         */
        "target"?: string | undefined;
    }
    interface CoreIcon {
        /**
          * Specifies the label to use for accessibility. Defaults to the icon name.
         */
        "ariaLabel"?: string;
        /**
          * Optional color of the icon. Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll | string;
        /**
          * A combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
         */
        "icon"?: iconsAll | string;
        /**
          * If enabled, core-icon will be loaded lazily when it's visible in the viewport.
         */
        "lazy"?: boolean;
        /**
          * Specifies which icon to use from `src/core-icons`.
         */
        "name"?: string;
        /**
          * The size of the icon. Available options are: `"16"` and `"24"`.
         */
        "size"?: "16" | "24";
        /**
          * Specifies the exact `src` of an SVG file to use.
         */
        "src"?: string;
    }
    interface CoreInput {
        /**
          * Boolean attribute lets you specify that a form control should have input focus when the page loads.
         */
        "autofocus"?: boolean;
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearInput"?: boolean;
        /**
          * Optional color of the label (inherited). Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsAll;
        /**
          * If `true`, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * If `true`, the pre-defined error state is applied.
         */
        "error"?: boolean;
        /**
          * The core-icon to render inside the text input.
         */
        "icon"?: string;
        /**
          * A hint to the browser for which keyboard to display.
         */
        "inputkeyboard"?: | "none"
    | "text"
    | "tel"
    | "url"
    | "email"
    | "numeric"
    | "decimal"
    | "search";
        /**
          * The label element associated with the element.
         */
        "label"?: string | undefined;
        /**
          * Sets the optional label to `inline` or `block` style [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display).
         */
        "labelDisplay"?: "block" | "inline";
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * Instructional placeholder text that shows before the element has a value.
         */
        "placeholder"?: string | undefined;
        /**
          * If `true`, the user must fill in a value before submitting a form.
         */
        "required"?: boolean;
        /**
          * Apply the large pre-defined element size and styling.
         */
        "size"?: "large";
        /**
          * If `true`, the pre-defined success state is applied.
         */
        "success"?: boolean;
        /**
          * How an <input> works varies considerably depending on the value of its type attribute, hence the different types are covered in their own separate reference pages. If this attribute is not specified, the default type adopted is `text`. [<input> types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
         */
        "type"?: string;
    }
    interface CoreLabel {
        /**
          * Optional color of the label. Use any `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: | "blue"
    | "green"
    | "yellow"
    | "red"
    | "white"
    | "black"
    | "blue-light-4"
    | "blue-light-3"
    | "blue-light-2"
    | "blue-light-1"
    | "blue-dark-1"
    | "blue-dark-2"
    | "blue-dark-3"
    | "blue-dark-4"
    | "green-light-4"
    | "green-light-3"
    | "green-light-2"
    | "green-light-1"
    | "green-dark-1"
    | "green-dark-2"
    | "green-dark-3"
    | "green-dark-4"
    | "yellow-light-4"
    | "yellow-light-3"
    | "yellow-light-2"
    | "yellow-light-1"
    | "yellow-dark-1"
    | "yellow-dark-2"
    | "yellow-dark-3"
    | "yellow-dark-4"
    | "red-light-4"
    | "red-light-3"
    | "red-light-2"
    | "red-light-1"
    | "red-dark-1"
    | "red-dark-2"
    | "red-dark-3"
    | "red-dark-4"
    | "gray-1"
    | "gray-2"
    | "gray-3"
    | "gray-4"
    | "gray-5"
    | "gray-6"
    | "gray-7"
    | "gray-8"
    | string;
        /**
          * If `true`, the user cannot interact with the nested element (typically core-input).
         */
        "disabled"?: boolean;
        /**
          * The display determines where and how the label behaves inside an item.
         */
        "display"?: "inline" | "block";
        /**
          * Applies the provided URL to the helpIcon href.
         */
        "helpurl"?: string | undefined;
    }
    interface CorePopover {
        /**
          * The popover visibility
         */
        "active"?: boolean;
        /**
          * The popover will show up when hovering the popover-trigger
         */
        "hoverable"?: boolean;
        /**
          * The popover variation.
         */
        "variation"?: "top" | "bottom";
    }
    interface CoreProgress {
        /**
          * Color of the progress bar.
         */
        "color"?: colorsPrimary;
        /**
          * The progress bar maximum value.
         */
        "max"?: number;
        /**
          * The pre-defined progress bar size.
         */
        "size"?: "small" | "large";
        /**
          * The progress bar value.
         */
        "value"?: number | undefined;
    }
    interface CoreRadio {
        /**
          * If applied, the element is checked.
         */
        "checked"?: boolean;
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The label element associated with the element.
         */
        "label"?: string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required"?: boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreSpinner {
        /**
          * Color of the spinner.
         */
        "color"?: colorsPrimary;
        /**
          * The pre-defined spinner size.
         */
        "size"?: "small" | "medium" | "large";
    }
    interface CoreTab {
        /**
          * If `true`, the tab element is set to active.
         */
        "active"?: boolean;
        /**
          * If `true`, the user cannot interact with the tab.
         */
        "disabled"?: boolean;
    }
    interface CoreTabGroup {
        /**
          * The pre-defined tab size.
         */
        "size"?: "small" | "large";
    }
    interface CoreTag {
        /**
          * Allows the tag to be closable and removed from the view.
         */
        "closable"?: boolean;
        /**
          * Optional color of the tag. Defaults to `black`. Use the following `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: colorsPrimary;
        /**
          * The pre-defined tag size.
         */
        "size"?: "small" | "large";
        /**
          * The tag variation.
         */
        "variation"?: "default" | "light";
    }
    interface CoreTextarea {
        /**
          * The visible width of the text control, in average character widths. If it is specified, it must be a positive integer.
         */
        "cols"?: number;
        /**
          * If `true`, the user cannot interact with the textarea.
         */
        "disabled"?: boolean;
        /**
          * The label element associated with the element.
         */
        "label"?: string | undefined;
        /**
          * Sets the optional label to `inline` or `block` style [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display).
         */
        "labelDisplay"?: "block" | "inline";
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * Instructional text that shows before the input has a value.
         */
        "placeholder"?: string | undefined;
        /**
          * If `true`, the user must fill in a value before submitting a form.
         */
        "required"?: boolean;
        /**
          * The number of visible text lines for the control.
         */
        "rows"?: number;
        /**
          * The value of the textarea.
         */
        "value"?: string | null;
    }
    interface CoreToast {
        /**
          * Optional color of the toast. Defaults to `black`.
         */
        "color"?: "white" | "green" | "yellow" | "red";
    }
    interface CoreToggle {
        /**
          * If applied, the element is rendered with the alternate styling.
         */
        "alt"?: boolean;
        /**
          * If applied, the element is checked.
         */
        "checked"?: boolean;
        /**
          * Optional color of the icon. Defaults to `blue`. Use the following `@color` in [core-primitives](https://unpkg.com/@core-ds/primitives/core-primitives.less) without `@color-`.
         */
        "color"?: "green" | "yellow" | "red" | "black" | "blue";
        /**
          * If applied, the user cannot interact with the element.
         */
        "disabled"?: boolean;
        /**
          * The label element associated with the element.
         */
        "label"?: string | undefined;
        /**
          * The label element position.
         */
        "labelPosition"?: labelPosition;
        /**
          * If applied, the user must fill in a value before submitting a form containing this element.
         */
        "required"?: boolean;
        /**
          * Apply the pre-defined large element size styling.
         */
        "size"?: "default" | "large";
    }
    interface CoreTooltip {
        /**
          * The tooltip visibility
         */
        "active"?: boolean;
        /**
          * The tooltip color
         */
        "color"?: "dark" | "light";
        /**
          * The tooltip will show up when hovering the tooltip-trigger
         */
        "hoverable"?: boolean;
        /**
          * The tooltip variation.
         */
        "variation"?: "top" | "bottom";
    }
    interface IntrinsicElements {
        "core-alert": CoreAlert;
        "core-badge": CoreBadge;
        "core-button": CoreButton;
        "core-checkbox": CoreCheckbox;
        "core-dropdown": CoreDropdown;
        "core-dropdown-item": CoreDropdownItem;
        "core-icon": CoreIcon;
        "core-input": CoreInput;
        "core-label": CoreLabel;
        "core-popover": CorePopover;
        "core-progress": CoreProgress;
        "core-radio": CoreRadio;
        "core-spinner": CoreSpinner;
        "core-tab": CoreTab;
        "core-tab-group": CoreTabGroup;
        "core-tag": CoreTag;
        "core-textarea": CoreTextarea;
        "core-toast": CoreToast;
        "core-toggle": CoreToggle;
        "core-tooltip": CoreTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-alert": LocalJSX.CoreAlert & JSXBase.HTMLAttributes<HTMLCoreAlertElement>;
            "core-badge": LocalJSX.CoreBadge & JSXBase.HTMLAttributes<HTMLCoreBadgeElement>;
            "core-button": LocalJSX.CoreButton & JSXBase.HTMLAttributes<HTMLCoreButtonElement>;
            "core-checkbox": LocalJSX.CoreCheckbox & JSXBase.HTMLAttributes<HTMLCoreCheckboxElement>;
            "core-dropdown": LocalJSX.CoreDropdown & JSXBase.HTMLAttributes<HTMLCoreDropdownElement>;
            "core-dropdown-item": LocalJSX.CoreDropdownItem & JSXBase.HTMLAttributes<HTMLCoreDropdownItemElement>;
            "core-icon": LocalJSX.CoreIcon & JSXBase.HTMLAttributes<HTMLCoreIconElement>;
            "core-input": LocalJSX.CoreInput & JSXBase.HTMLAttributes<HTMLCoreInputElement>;
            "core-label": LocalJSX.CoreLabel & JSXBase.HTMLAttributes<HTMLCoreLabelElement>;
            "core-popover": LocalJSX.CorePopover & JSXBase.HTMLAttributes<HTMLCorePopoverElement>;
            "core-progress": LocalJSX.CoreProgress & JSXBase.HTMLAttributes<HTMLCoreProgressElement>;
            "core-radio": LocalJSX.CoreRadio & JSXBase.HTMLAttributes<HTMLCoreRadioElement>;
            "core-spinner": LocalJSX.CoreSpinner & JSXBase.HTMLAttributes<HTMLCoreSpinnerElement>;
            "core-tab": LocalJSX.CoreTab & JSXBase.HTMLAttributes<HTMLCoreTabElement>;
            "core-tab-group": LocalJSX.CoreTabGroup & JSXBase.HTMLAttributes<HTMLCoreTabGroupElement>;
            "core-tag": LocalJSX.CoreTag & JSXBase.HTMLAttributes<HTMLCoreTagElement>;
            "core-textarea": LocalJSX.CoreTextarea & JSXBase.HTMLAttributes<HTMLCoreTextareaElement>;
            "core-toast": LocalJSX.CoreToast & JSXBase.HTMLAttributes<HTMLCoreToastElement>;
            "core-toggle": LocalJSX.CoreToggle & JSXBase.HTMLAttributes<HTMLCoreToggleElement>;
            "core-tooltip": LocalJSX.CoreTooltip & JSXBase.HTMLAttributes<HTMLCoreTooltipElement>;
        }
    }
}
