/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreImage {
        /**
          * The image alt tag. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt)
         */
        "alt": string;
        /**
          * The intrinsic height of the image, in pixels. Must be an integer without a unit. Overwritten with `height: auto` by default, but should be included.
         */
        "height": number;
        /**
          * The image source path without file extension. On browsers supporting `srcset`, `src` is treated as the fallback image with a 1x pixel density.
         */
        "src": string;
        /**
          * The intrinsic width of the image, in pixels. Must be an integer without a unit.
         */
        "width": number;
    }
}
declare global {
    interface HTMLCoreImageElement extends Components.CoreImage, HTMLStencilElement {
    }
    var HTMLCoreImageElement: {
        prototype: HTMLCoreImageElement;
        new (): HTMLCoreImageElement;
    };
    interface HTMLElementTagNameMap {
        "core-image": HTMLCoreImageElement;
    }
}
declare namespace LocalJSX {
    interface CoreImage {
        /**
          * The image alt tag. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt)
         */
        "alt"?: string;
        /**
          * The intrinsic height of the image, in pixels. Must be an integer without a unit. Overwritten with `height: auto` by default, but should be included.
         */
        "height"?: number;
        /**
          * The image source path without file extension. On browsers supporting `srcset`, `src` is treated as the fallback image with a 1x pixel density.
         */
        "src"?: string;
        /**
          * The intrinsic width of the image, in pixels. Must be an integer without a unit.
         */
        "width"?: number;
    }
    interface IntrinsicElements {
        "core-image": CoreImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-image": LocalJSX.CoreImage & JSXBase.HTMLAttributes<HTMLCoreImageElement>;
        }
    }
}
